# Generated by Django 3.2.7 on 2021-09-08 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import register.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, validators=[register.validators.validate_CNPJ, register.validators.valida_cnpj], verbose_name='CNPJ')),
                ('email', models.EmailField(max_length=50)),
                ('status', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=90)),
                ('city', models.CharField(max_length=30)),
                ('managers', models.ManyToManyField(blank=True, related_name='company', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Company',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True, validators=[register.validators.validate_CPF], verbose_name='CPF')),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
