# Generated by Django 3.2.7 on 2021-09-08 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='document',
            field=models.FileField(null=True, upload_to='meusarquivos'),
        ),
    ]
