# Generated by Django 3.2.7 on 2021-10-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_company',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='name_company',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
