# Generated by Django 3.2.7 on 2021-10-15 13:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20211015_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='useres',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
