# Generated by Django 3.2.7 on 2021-10-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_alter_company_useres'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AddField(
            model_name='company',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='admin status'),
        ),
    ]
