# Generated by Django 3.2.7 on 2021-10-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_alter_user_company_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_company',
        ),
        migrations.AddField(
            model_name='user',
            name='document',
            field=models.FileField(null=True, upload_to='meusarquivos'),
        ),
    ]
