# Generated by Django 3.2.7 on 2021-10-15 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20211015_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='is_admin',
        ),
    ]
