# Generated by Django 3.2.7 on 2021-09-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20210909_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='company',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='client',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo de Usuário'),
        ),
    ]
