# Generated by Django 3.2.7 on 2021-10-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_remove_company_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='useres',
            field=models.ManyToManyField(to='register.Client'),
        ),
    ]
