# Generated by Django 3.2.7 on 2021-10-04 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_alter_user_company_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name_company',
            new_name='name',
        ),
    ]
