# Generated by Django 3.2.7 on 2021-10-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_alter_company_useres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='company_id',
        ),
        migrations.AlterField(
            model_name='company',
            name='useres',
            field=models.ManyToManyField(to='register.Client'),
        ),
    ]
