# Generated by Django 3.2.7 on 2021-10-15 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_auto_20211015_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.company'),
        ),
    ]
