# Generated by Django 3.2.7 on 2021-10-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_user_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='useres',
            field=models.ManyToManyField(to='register.Company'),
        ),
    ]
