# Generated by Django 3.2.7 on 2021-10-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_alter_company_useres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='useres',
            field=models.ManyToManyField(to='register.Client'),
        ),
    ]
