# Generated by Django 3.2.7 on 2021-10-19 11:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_alter_company_useres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='useres',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
